{% set provider = "opc" %}
{% set goname = "github.com/terraform-providers/terraform-provider-"+provider.lower() %}
{% set version = "1.4.0" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

{% set x4_plugin = name + '_v' + version + "_x4" + (".exe" if win else "")%}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: f369d1823f284ee5ebb4c61bb01bf6dffe097ea4a714ea20e44e9471d2e873bb

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go build -v -o $GOBIN/{{ x4_plugin }} .  # [unix]
    - go build -v -o %GOBIN%\{{ x4_plugin }} .  # [win]

requirements:
  build:
    - {{ compiler('go') }} >=1.11.3
  run:
    - terraform >=0.10  # [unix]
    - terraform >=0.11.11  # [win]

test:
  requires:
    - m2-bash       # [win]
    - m2-coreutils  # [win]
  commands:
    - bash -euf -c "echo 'provider \"{{ provider|lower }}\" { version=\"{{ version }}\" }' > init.tf"
    - terraform init
    # Tests that no plugins were downloaded
    - test -f .terraform/plugins/{{ goos }}_{{ goarch }}/lock.json
    - test ! -f .terraform/plugins/{{ goos }}_{{ goarch }}/{{ x4_plugin }}

about:
  home: https://www.terraform.io
  license: MPL-2.0
  summary: The Terraform Oracle Public Cloud provider
  doc_url: https://www.terraform.io/docs/providers/{{ provider }}/index.html
  dev_url: https://github.com/terraform-providers/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/terraform
