appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: t2WHgz6WsOX7M3LFArHJ3wId2t6CetimM1tlKsimTjqRtI2pPdFitzgCSHGY0qHg9fVEOlPLzk929qvTyNg9ZfOMT4BlwKUmSW3qgq62umTV2jKI2b+v1wfEfIdUkGNpkVqsc2G5vN69lsmWekPJtrWsrHY12dlzSTKjYve+VbPHaddrSb2ICqBAKsFed8kdJXaE4K66iMYXa7FK71wCjVTcLaM0Z6C9uMM+C3cehm+wr6MBYOHKntwkGcwsj75jeTTx/dFWBJQbzPbevV8t+LlvUAe1F2R5bLdl3Z7HDbN2z63hLhv8S5mXjhJBNJq6aosBPIBwLHam5GfovdJxFmNjzNvceRYBgkIslL34ppGDTrHFJBXmG/3xOO2Me0AuIcOmfSrCAx0E8hI6dXRyLtmR4wqo31rDgoj98aeUE3EnWdOFqbmDod1B0QF4apzFD9hLMEgkI276B45Uld4ZGtvs97nrG1Y/5RckqB7Zipv6K+DgDxnfyAewS7FB5MB2y3owqYP1PpkZzjrYf8AP3DvRqlRa4kRRWO0fKLzKrMkHsSTrHnziY/cLBCjuYnO33HcUus4x1/vHIuKTrU/mckfwIC4CysSFdjROebukTBpgo3eBGdtHv/lvRjP9VGHis4P+zHGv6eRPQ4cq2yZejRp8CHjegisd6MlU30ojUtU=}
provider:
  win: azure
bot:
  automerge: true
